#!/usr/bin/env bash
#
# Point a local `npm run dev` at the deployed cloud stack: the Managed
# Postgres cluster and the live webhook trigger.
#
# This is how you run the app locally at all — there is no local database, so
# a local process talks to the same cluster App Platform does. Also the way to
# keep the demo working when the App Platform URL is awkward to reach.
#
#   ./scripts/link-local.sh > .env.local
#   npm run dev            # dotenv loads .env, then .env.local wins
#
# Writes to stdout so nothing is clobbered by accident. Contains credentials.

set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

[ -f .deploy-state.json ] || { echo "no .deploy-state.json — run ./deploy.sh first" >&2; exit 1; }
set -a; . ./.env; set +a
export DIGITALOCEAN_ACCESS_TOKEN

: "${DB_NAME:=complaints}"   # same default and override as deploy.sh

db_id="$(jq -r .db_cluster_id .deploy-state.json)"
conn="$(doctl databases connection "$db_id" --output json)"
pick() { echo "$conn" | jq -r "if type==\"array\" then .[0] else . end | .$1"; }
ca="$(doctl databases get-ca "$db_id" --output json | jq -r 'if type=="array" then .[0] else . end | .certificate')"

cat <<EOF
# Generated by scripts/link-local.sh — local UI against the deployed stack.
# Contains credentials. Gitignored via .env.* — do not commit.

NODE_ENV=development
PORT=3000

# The deployed Managed Postgres cluster. There is no local database.
DATABASE_URL=postgresql://$(pick user):$(pick password)@$(pick host):$(pick port)/${DB_NAME}?sslmode=require
DB_CA_CERT=${ca}

# Submissions fire the real webhook trigger, so real microVMs write the rows
# and this process only ever reads them back.
MARS_WEBHOOK_URL=$(jq -r .webhook_url .deploy-state.json)
MARS_WEBHOOK_SECRET=$(jq -r .webhook_secret .deploy-state.json)
MARS_TICKET_TABLE=tickets
RESET_WEBHOOK_URL=$(jq -r '.reset_webhook_url // empty' .deploy-state.json)
RESET_WEBHOOK_SECRET=$(jq -r '.reset_webhook_secret // empty' .deploy-state.json)
EOF
