#!/usr/bin/env bash
#
# Point a local `npm run dev` at the deployed cloud stack: the Managed
# Postgres cluster and the live webhook trigger. Useful when the App Platform
# URL is awkward to reach (corporate policy, no internet on stage) but you
# still want the real agents and the real database behind the UI.
#
#   ./scripts/link-local.sh > .env.local
#   npm run dev            # dotenv loads .env, then .env.local wins
#
# Writes to stdout so nothing is clobbered by accident. Contains credentials.

set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

[ -f .deploy-state.json ] || { echo "no .deploy-state.json — run ./deploy.sh first" >&2; exit 1; }
set -a; . ./.env; set +a
export DIGITALOCEAN_ACCESS_TOKEN

db_id="$(jq -r .db_cluster_id .deploy-state.json)"
conn="$(doctl databases connection "$db_id" --output json)"
pick() { echo "$conn" | jq -r "if type==\"array\" then .[0] else . end | .$1"; }
ca="$(doctl databases get-ca "$db_id" --output json | jq -r 'if type=="array" then .[0] else . end | .certificate')"

cat <<EOF
# Generated by scripts/link-local.sh — local UI against the deployed stack.
# Contains credentials. Gitignored via .env.* — do not commit.

NODE_ENV=development
PORT=3000

# The deployed Managed Postgres cluster, not the local SQLite file.
DB_DRIVER=postgres
DATABASE_URL=postgresql://$(pick user):$(pick password)@$(pick host):$(pick port)/complaints?sslmode=require
DB_CA_CERT=${ca}

# Submissions fire the real webhook trigger, so real microVMs write the rows
# and this process only ever reads them back.
INGEST_MODE=mars
MARS_WEBHOOK_URL=$(jq -r .webhook_url .deploy-state.json)
MARS_WEBHOOK_SECRET=$(jq -r .webhook_secret .deploy-state.json)
MARS_TICKET_TABLE=tickets
EOF
